services:
  localstack:
    container_name: pedidos-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
    # volumes:
    #   - ./localstack:/tmp/localstack
