version: '3.8'

services:
  pedidos-postgres:
    image: postgres:15
    container_name: pedidos-postgres
    environment:
      POSTGRES_DB: pedidosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jpmaion498
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pedidos-network

  pedidos-localstack:
    image: localstack/localstack:latest
    container_name: pedidos-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEFAULT_REGION=us-east-1
    networks:
      - pedidos-network



  pedidos-api:
    build:
      context: .
      dockerfile: Pedido.Api/Dockerfile
    container_name: pedidos-api
    ports:
      - "8080:80"
    environment:      
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=pedidos-postgres;Port=5432;Database=pedidosdb;Username=postgres;Password=jpmaion498
    depends_on:
      - pedidos-postgres
      - pedidos-localstack
    networks:
      - pedidos-network

volumes:
  postgres_data:

networks:
  pedidos-network:
    driver: bridge
